name: Publish PlexyWeChatPayInternal.podspec
on: [workflow_dispatch]
jobs:

  publish:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4

    - name: Select latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Publish PlexyWeChatPayInternal.podspec
      run: |
        gem install cocoapods
        pod trunk push PlexyWeChatPayInternal.podspec --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
